fix: pipeline

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -39,35 +39,41 @@ jobs:
         mv allure-$ALLURE_VERSION /opt/allure
         # Add Allure to PATH
         echo "/opt/allure/bin" >> $GITHUB_PATH
-        allure --version
+        allure --version  # Check if allure is accessible
 
     # Ensure Allure report generation step always runs
-    - name: Copy Allure Data from Previous Runs
-      if: always()
+    - name: Check allure-results Directory
       run: |
-        mkdir -p allure-results/previous/
+        echo "Checking for allure-results directory..."
         if [ -d allure-results ]; then
-          cp -r allure-results/* allure-results/previous/ || echo "No previous allure results to copy."
+          echo "allure-results exists."
+          ls -la allure-results
+        else
+          echo "allure-results does not exist."
         fi
 
     - name: Generate Allure Report
-      if: always()
-      run: allure generate allure-results --clean -o allure-report
+      run: |
+        echo "Generating Allure report..."
+        if [ -d allure-results ]; then
+          allure generate allure-results --clean -o allure-report
+        else
+          echo "Cannot generate report, allure-results not found."
+        fi
       env:
         LOGIN: ${{ secrets.LOGIN }}
         PASSWORD: ${{ secrets.PASSWORD }}
         EMAIL: ${{ secrets.EMAIL }}
 
     - name: Checkout target branch
-      if: always()
       uses: actions/checkout@v4
       with:
         ref: gh-pages
 
     # Conditional copying and deleting of allure report directory
     - name: Copy Allure Report to gh-pages branch
-      if: always()
       run: |
+        echo "Copying Allure report to gh-pages branch..."
         if [ -d allure-report ]; then
           echo "Copying Allure report..."
           mkdir -p ./allure-report/
@@ -77,10 +83,9 @@ jobs:
         fi
 
     - name: Debug List contents of Allure Report
-      run: ls -la allure-report
+      run: ls -la allure-report || echo "allure-report directory does not exist."
 
     - name: Commit and Push Allure Report
-      if: always()
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       run: |
@@ -92,5 +97,4 @@ jobs:
         git push origin gh-pages
 
     - name: Confirm GitHub Pages Setup
-      if: always()
       run: echo "GitHub Pages is set up on the 'gh-pages' branch."
